// ------------------------------------------------------ //
// ----- Autogenerated by xls2json - do not modify! ----- //
// ------------------------------------------------------ //

public class SampleData : Data
{
	// Item name loc key
	public readonly string name;

	// Item cost
	public readonly int price;

	// Item health
	public readonly float health;

	// Is this item super cool?
	public readonly bool fancy;

	// Item max health
	public readonly float maxHealth;

}
